/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Administrador;

import java.awt.CardLayout;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Pedro Henrique
 */
public class Administrador extends javax.swing.JFrame {

    private CardLayout layout;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Administrador.class.getName());

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

        layout = new CardLayout();
        painelPrincipal.setLayout(layout);

        painelPrincipal.add(spCorretores, "corretores");
        painelPrincipal.add(spClientes, "clientes");
        painelPrincipal.add(spImoveis, "imoveis");
        painelPrincipal.add(spContratos, "contratos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spCorretores = new javax.swing.JScrollPane();
        tableCorretores = new javax.swing.JTable();
        spClientes = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        spImoveis = new javax.swing.JScrollPane();
        tableImoveis = new javax.swing.JTable();
        spContratos = new javax.swing.JScrollPane();
        tableContratos = new javax.swing.JTable();
        PainelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonLCorretores = new javax.swing.JButton();
        buttonLClientes = new javax.swing.JButton();
        buttonLImoveis = new javax.swing.JButton();
        buttonLContratos = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        painelPrincipal = new javax.swing.JPanel();

        tableCorretores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE", "CARGO", "ADMISSAO", "ID ADM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spCorretores.setViewportView(tableCorretores);

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spClientes.setViewportView(tableClientes);

        tableImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spImoveis.setViewportView(tableImoveis);

        tableContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spContratos.setViewportView(tableContratos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bem-vindo Sr. ");

        buttonLCorretores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLCorretores.setText("Lista Corretores");
        buttonLCorretores.addActionListener(this::buttonLCorretoresActionPerformed);

        buttonLClientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLClientes.setText("Lista Clientes");
        buttonLClientes.addActionListener(this::buttonLClientesActionPerformed);

        buttonLImoveis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLImoveis.setText("Lista Imóveis");
        buttonLImoveis.addActionListener(this::buttonLImoveisActionPerformed);

        buttonLContratos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLContratos.setText("Lista Contratos");
        buttonLContratos.addActionListener(this::buttonLContratosActionPerformed);

        Button5.setText("Novo Funcionário");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(buttonLCorretores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Button5))
                .addGap(62, 62, 62)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLCorretores)
                    .addComponent(buttonLClientes)
                    .addComponent(buttonLImoveis)
                    .addComponent(buttonLContratos))
                .addGap(36, 36, 36)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLCorretoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLCorretoresActionPerformed
        layout.show(painelPrincipal, "corretores");
    }//GEN-LAST:event_buttonLCorretoresActionPerformed

    private void buttonLClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLClientesActionPerformed
        layout.show(painelPrincipal, "clientes");
    }//GEN-LAST:event_buttonLClientesActionPerformed

    private void buttonLImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLImoveisActionPerformed
        layout.show(painelPrincipal, "imoveis");
    }//GEN-LAST:event_buttonLImoveisActionPerformed

    private void buttonLContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLContratosActionPerformed
        layout.show(painelPrincipal, "contratos");
    }//GEN-LAST:event_buttonLContratosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Administrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button5;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton buttonLClientes;
    private javax.swing.JButton buttonLContratos;
    private javax.swing.JButton buttonLCorretores;
    private javax.swing.JButton buttonLImoveis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane spClientes;
    private javax.swing.JScrollPane spContratos;
    private javax.swing.JScrollPane spCorretores;
    private javax.swing.JScrollPane spImoveis;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableContratos;
    private javax.swing.JTable tableCorretores;
    private javax.swing.JTable tableImoveis;
    // End of variables declaration//GEN-END:variables
}
