/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Administrador;

import DAO.FuncionarioDAO;
import DAO.FuncionarioDAO.Sessao;
import Model.Funcionario;
import View.CadastroFuncionario.CadastroFuncionario;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Panel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Pedro Henrique
 */
public class Administrador extends javax.swing.JFrame {

    private CardLayout layout;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Administrador.class.getName());

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

        Dimension dimension = new Dimension();
        dimension.setSize(800, 300);

        layout = new CardLayout();
        painelPrincipal.setLayout(layout);

        painelPrincipal.add(spInicial, "inicial");
        painelPrincipal.add(spBuscaPersonalizadaNome, "buscaPersonalizada");
        painelPrincipal.add(spCorretores, "corretores");
        painelPrincipal.add(spClientes, "clientes");
        painelPrincipal.add(spImoveis, "imoveis");
        painelPrincipal.add(spContratos, "contratos");
        layout.show(painelPrincipal, "inicial");

        PainelPrincipal.setSize(990, 700);
        painelPrincipal.setPreferredSize(dimension);
        setSize(new Dimension(1000, 736));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spInicial = new javax.swing.JScrollPane();
        panelInicial = new javax.swing.JPanel();
        spBuscaPersonalizadaNome = new javax.swing.JScrollPane();
        tableBuscaPersonalizadaNome = new javax.swing.JTable();
        spCorretores = new javax.swing.JScrollPane();
        tableCorretores = new javax.swing.JTable();
        spClientes = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        spImoveis = new javax.swing.JScrollPane();
        tableImoveis = new javax.swing.JTable();
        spContratos = new javax.swing.JScrollPane();
        tableContratos = new javax.swing.JTable();
        PainelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonLCorretores = new javax.swing.JButton();
        buttonLClientes = new javax.swing.JButton();
        buttonLImoveis = new javax.swing.JButton();
        buttonLContratos = new javax.swing.JButton();
        buttonNovoFuncionario = new javax.swing.JButton();
        painelPrincipal = new javax.swing.JPanel();
        labelNomeFuncionario = new javax.swing.JLabel();
        tfBuscarNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        spInicial.setViewportView(panelInicial);

        tableBuscaPersonalizadaNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE", "CARGO", "ID ADM"
            }
        ));
        tableBuscaPersonalizadaNome.setShowGrid(true);
        spBuscaPersonalizadaNome.setViewportView(tableBuscaPersonalizadaNome);

        tableCorretores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE", "CARGO", "ID ADM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spCorretores.setViewportView(tableCorretores);

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spClientes.setViewportView(tableClientes);

        tableImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TÍTULO", "ENDEREÇO", "DESCRIÇÃO", "TIPO", "PREÇO", "INTENÇÃO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spImoveis.setViewportView(tableImoveis);

        tableContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spContratos.setViewportView(tableContratos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Olá,");

        buttonLCorretores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLCorretores.setText("Lista Corretores");
        buttonLCorretores.addActionListener(this::buttonLCorretoresActionPerformed);

        buttonLClientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLClientes.setText("Lista Clientes");
        buttonLClientes.addActionListener(this::buttonLClientesActionPerformed);

        buttonLImoveis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLImoveis.setText("Lista Imóveis");
        buttonLImoveis.addActionListener(this::buttonLImoveisActionPerformed);

        buttonLContratos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLContratos.setText("Lista Contratos");
        buttonLContratos.addActionListener(this::buttonLContratosActionPerformed);

        buttonNovoFuncionario.setText("Novo Funcionário");
        buttonNovoFuncionario.addActionListener(this::buttonNovoFuncionarioActionPerformed);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        labelNomeFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeFuncionario.setText("Administrador");

        tfBuscarNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Busca Personalizada:");

        buttonSair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(this::buttonSairActionPerformed);

        buttonBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(this::buttonBuscarActionPerformed);

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(buttonLCorretores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNomeFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buttonNovoFuncionario)
                    .addComponent(labelNomeFuncionario))
                .addGap(62, 62, 62)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLCorretores)
                    .addComponent(buttonLClientes)
                    .addComponent(buttonLImoveis)
                    .addComponent(buttonLContratos))
                .addGap(34, 34, 34)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonBuscar))
                .addGap(41, 41, 41)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(buttonSair)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(987, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLCorretoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLCorretoresActionPerformed
        layout.show(painelPrincipal, "corretores");

        FuncionarioDAO funcDAO = new FuncionarioDAO();

        List<Funcionario> lista = funcDAO.listarCorretoresAdm(Sessao.idAdministrador);

        DefaultTableModel modelo = (DefaultTableModel) tableCorretores.getModel();
        modelo.setRowCount(0);

        for (Funcionario func : lista) {
            modelo.addRow(new Object[]{
                func.getIdFuncionario(),
                func.getNome(),
                func.getEmail(),
                func.getTelefone(),
                func.getCargo(),
                func.getIdAdministrador()
            });
        }
    }//GEN-LAST:event_buttonLCorretoresActionPerformed

    private void buttonLClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLClientesActionPerformed
        layout.show(painelPrincipal, "clientes");
    }//GEN-LAST:event_buttonLClientesActionPerformed

    private void buttonLImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLImoveisActionPerformed
        layout.show(painelPrincipal, "imoveis");
    }//GEN-LAST:event_buttonLImoveisActionPerformed

    private void buttonLContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLContratosActionPerformed
        layout.show(painelPrincipal, "contratos");
    }//GEN-LAST:event_buttonLContratosActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoFuncionarioActionPerformed
        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        cadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_buttonNovoFuncionarioActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

        DefaultTableModel modelo = (DefaultTableModel) tableBuscaPersonalizadaNome.getModel();

        modelo.setRowCount(0);

        String buscarNome = tfBuscarNome.getText();

        List<Funcionario> lista = funcionarioDAO.listarFuncionarioNome(buscarNome);

        layout.show(painelPrincipal, "buscaPersonalizada");

        modelo.setRowCount(0);

        for (Funcionario func : lista) {
            modelo.addRow(new Object[]{
                func.getIdFuncionario(),
                func.getNome(),
                func.getEmail(),
                func.getTelefone(),
                func.getCargo(),
                func.getIdAdministrador()
            });
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    public void setNomeFuncionario(String nome) {
        labelNomeFuncionario.setText(nome);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Administrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonLClientes;
    private javax.swing.JButton buttonLContratos;
    private javax.swing.JButton buttonLCorretores;
    private javax.swing.JButton buttonLImoveis;
    private javax.swing.JButton buttonNovoFuncionario;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel labelNomeFuncionario;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JScrollPane spBuscaPersonalizadaNome;
    private javax.swing.JScrollPane spClientes;
    private javax.swing.JScrollPane spContratos;
    private javax.swing.JScrollPane spCorretores;
    private javax.swing.JScrollPane spImoveis;
    private javax.swing.JScrollPane spInicial;
    private javax.swing.JTable tableBuscaPersonalizadaNome;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableContratos;
    private javax.swing.JTable tableCorretores;
    private javax.swing.JTable tableImoveis;
    private javax.swing.JTextField tfBuscarNome;
    // End of variables declaration//GEN-END:variables
}
